name: Run Tailscale Exit Node

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tailscale
        run: curl -fsSL https://tailscale.com/install.sh | sh
      - name: Start Tailscale Server
        run: sudo tailscale up --advertise-exit-node --auth-key=${{ secrets.TS_TOKEN }}
      - name: Waiting...
        run: sleep 340m
